#S1
FROM maven:3.9.6-eclipse-temurin-21-alpine AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

#S2
FROM amazoncorretto:21.0.4-alpine3.18
WORKDIR /app
COPY --from=build /app/target/tasktracker-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT [ "java", "-jar", "app.jar" ]

